name: wiki
#
#  Compose file for DockerWiki.
#
services:

  view:
    image: $DW_HID/mediawiki:$DW_TAG
    depends_on:
      - data
    environment:
      - DW_TZ=${DW_TZ}
    hostname: $VIEW_HOST
    networks:
      - net
    ports:
      - "${MW_PORTS}"

  data:
    image: $DW_HID/mariadb:$DW_TAG
    environment:
      - DW_TZ=${DW_TZ}
    hostname: $DATA_HOST
    networks:
      - net
    volumes:
      - data:/var/lib/mysql

networks:
  net:

volumes:
  data:
