name: wiki
#
#  Compose file for DockerWiki.
#
services:

  view:
    image: $DID/mediawiki:$TAG
    depends_on:
      - data
    environment:
      - TZ=${TZ}
    hostname: view
    networks:
      - net
    ports:
      - "${MW_PORTS}"

  data:
    image: $DID/mariadb:$TAG
    environment:
      - TZ=${TZ}
    hostname: data
    networks:
      - net
    volumes:
      - data:/var/lib/mysql

networks:
  net:

volumes:
  data:
