name: wiki
#
#  Compose file for DockerWiki.
#
#  Caveat: Docker composer cache can be sticky. If you get stuck and
#  just want a quick code/debug cycle, try using cake.sh (which only uses
#  Dockerfiles, not Compose files) to create and destroy this system.
#
services:

  view:
    image: $DID/mediawiki:$TAG
    build:
      context: ./mediawiki
      tags:
        - "$DID/mediawiki:$TAG"
        - "$DID/mediawiki:latest"
    depends_on:
      - data
    environment:
      - TZ=${TZ}
    hostname: view
    networks:
      - net
    ports:
      - "${PORTS}"

  data:
    image: $DID/mariadb:$TAG
    build:
      context: ./mariadb
      tags:
        - '$DID/mariadb:$TAG'
        - '$DID/mariadb:latest'
      args:
        # https://stackoverflow.com/q/76229692
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - MARIADB_ROOT_HOST=${MARIADB_ROOT_HOST}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PASSWORD_HASH=${MARIADB_PASSWORD_HASH}
    environment:
      - TZ=${TZ}
    hostname: data
    networks:
      - net
    volumes:
      - data:/var/lib/mysql

networks:
  net:

volumes:
  data:
