name: wiki
services:
  data:
    environment:
      DW_TZ: UTC
    hostname: wiki-data-1
    image: idave2/mariadb:1.1.0
    networks:
      net: null
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
        volume: {}
  view:
    depends_on:
      data:
        condition: service_started
        required: true
    environment:
      DW_TZ: UTC
    hostname: wiki-view-1
    image: idave2/mediawiki:1.1.0
    networks:
      net: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        published: "8080"
        protocol: tcp
networks:
  net:
    name: wiki_net
volumes:
  data:
    name: wiki_data
